name: health_ia_care_app
description: "An AI coach application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^9.2.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^9.2.0
  google_fonts: ^7.0.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  language_code: ^0.5.5
  logging: ^1.3.0
  material_symbols_icons: ^4.2892.0
  mocktail: ^1.0.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
